baseURL = "https://TODO.dev"

# canonifyURLs = true
languageCode = "en-us"
title = "The Mark Gable Foundation"
disableKinds = ["RSS"]

DefaultContentLanguage = "en"
hasCJKLanguage = true
EnableMissingTranslationPlaceholders = true

uglyURLs = false

[mediaTypes]
[mediaTypes."text/markdown"]
suffixes = ["md"]

[mediaTypes."text/plain"]
suffixes = ["txt"]

[mediaTypes."text/asciidoc"]
suffixes = ["adoc"]

[outputs]
home = ["html"]
page = ["html"]
